[[themes]]
name = "main"
[themes.palette]
foreground = "#DAAC9B"
black = "#FFFFFF"
red = "#CE9F7B"
green = "#CE9F7B"
yellow = "#CE9F7B"
blue = "#CE9F7B"
magenta = "#CE9F7B"
cyan = "#F5D6AB"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#d6d4d4"
bright_yellow = "#f1fa8c"
bright_blue = "#ff0000"
bright_magenta = "#ff79c6"
bright_cyan = "#ff0000"
bright_white = "#ffffff"
